runtime: python311

env_variables:
  # This setting is used in settings.py to configure your ALLOWED_HOSTS
  APPENGINE_URL: https://deploy-django-412012.ew.r.appspot.com

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/

- url: /.*
  script: auto
# [END gaestd_py_django_app_yaml]
# [END django_app]